// AUTO-GENERATED BY secure_localizations. DO NOT EDIT.
import 'dart:convert';
import 'dart:typed_data';

class SecureEncryption {
  static const int _key = 37433831;
  static const int _byteKey = _key & 0xFF;

  static String decode(String encodedBase64) {
    try {
      final Uint8List bytes = base64.decode(encodedBase64);
      final List<int> decoded = bytes.map((int b) => b ^ _byteKey).toList();
      return utf8.decode(decoded);
    } catch (e) {
      return encodedBase64;
    }
  }
}
